name: Github Pages Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.4]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and build
        run: npm install && npm run gh-build && cp dist/mboalab/index.html dist/mboalab/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: mboalab/dist/mboalab # The folder the action should deploy.
